[tool.poetry]
name = "mlx-esm"
version = "0.1.0"
description = ""
authors = ["Usman Masood <usmanm@fastmail.fm>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
